### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by 13qwertyp** [anarchysmo/HWIDSpoofer#6]
virus?

**Comment by iparamsh** [comment]
I literally posted the source code, just read it if you are not sure.

**Comment by 13qwertyp** [comment]
![image](https://user-images.githubusercontent.com/92000383/155441868-c6554c38-52b8-4908-a869-a626061bfc0e.png)
is this ? sorry i have trust issue

**Comment by iparamsh** [comment]
it's not, virustotal says that because this software is touching your registry and WMI to change ID's.

**Comment by iparamsh** [comment]
you can go to details and ig it should show you libraries that was used in this project like "using System;" or something like that. I didn't use any libraries to send packets, so you should not see em there

**Comment by 13qwertyp** [comment]
this works for valorant or it isn't?

**Comment by iparamsh** [comment]
> this works for valorant or it isn't?

It is user mode spoofer, riot AC uses kernel mode. So, no. You will not be able to find one open source working spoofer since to make a working valo spoofer you need to make a kernel driver. Kernel drivers are have to be done carefully and for the particular winver. Public sus kernel modes are being banned by the AC. So, there is only 2 options make one by yourself or buy one. If you want to know more ANARCHYSMO#6666
